// <auto-generated />
using System;
using EquipmentManagementPlatform.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EquipmentManagementPlatform.Repository.Migrations
{
    [DbContext(typeof(EquipmentContext))]
    partial class EquipmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EquipmentEntityEquipmentHistoricStateEntity", b =>
                {
                    b.Property<int>("EquipmentEntityId")
                        .HasColumnType("int");

                    b.Property<int>("HistoricStatesId")
                        .HasColumnType("int");

                    b.HasKey("EquipmentEntityId", "HistoricStatesId");

                    b.HasIndex("HistoricStatesId");

                    b.ToTable("EquipmentEntityEquipmentHistoricStateEntity");
                });

            modelBuilder.Entity("EquipmentManagementPlatform.Repository.Entity.EquipmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("AssignedOrders")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CurrentOrder")
                        .HasColumnType("int");

                    b.Property<string>("FaultMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOperational")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OverallEquipmentEffectiveness")
                        .HasColumnType("float");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedOrders = "[5443]",
                            CurrentOrder = 5443,
                            FaultMessage = "",
                            IsOperational = true,
                            Location = "A1.01",
                            Name = "EQ758490",
                            Operator = "EMP123 - FirstName1 LastName1",
                            OverallEquipmentEffectiveness = 98.200000000000003,
                            State = "GREEN"
                        },
                        new
                        {
                            Id = 2,
                            AssignedOrders = "[]",
                            FaultMessage = "Machine is blocked",
                            IsOperational = false,
                            Location = "A2.11",
                            Name = "EQ125896",
                            Operator = "EMP666 - FirstName2 LastName2 ",
                            OverallEquipmentEffectiveness = 12.0,
                            State = "RED"
                        },
                        new
                        {
                            Id = 3,
                            AssignedOrders = "[]",
                            FaultMessage = "",
                            IsOperational = true,
                            Location = "B3.11",
                            Name = "EQ147852",
                            Operator = "EMP006 - FirstName3 LastName3 ",
                            OverallEquipmentEffectiveness = 76.5,
                            State = "YELLOW"
                        },
                        new
                        {
                            Id = 4,
                            AssignedOrders = "[1111]",
                            CurrentOrder = 1111,
                            FaultMessage = "",
                            IsOperational = true,
                            Location = "B3.07",
                            Name = "EQ125987",
                            Operator = "EMP223 - FirstName4 LastName4 ",
                            OverallEquipmentEffectiveness = 96.700000000000003,
                            State = "GREEN"
                        },
                        new
                        {
                            Id = 5,
                            AssignedOrders = "[]",
                            FaultMessage = "",
                            IsOperational = true,
                            Location = "B3.01",
                            Name = "EQ136574",
                            Operator = "EMP874 - FirstName5 LastName5 ",
                            OverallEquipmentEffectiveness = 77.900000000000006,
                            State = "RED"
                        },
                        new
                        {
                            Id = 6,
                            AssignedOrders = "[]",
                            FaultMessage = "",
                            IsOperational = true,
                            Location = "C2.02",
                            Name = "EQ174444",
                            Operator = "",
                            OverallEquipmentEffectiveness = 84.400000000000006,
                            State = "YELLOW"
                        },
                        new
                        {
                            Id = 7,
                            AssignedOrders = "[2222]",
                            CurrentOrder = 2222,
                            FaultMessage = "",
                            IsOperational = true,
                            Location = "C3.03",
                            Name = "EQ195874",
                            Operator = "EMP999 - FirstName6 LastName6 ",
                            OverallEquipmentEffectiveness = 99.5,
                            State = "GREEN"
                        },
                        new
                        {
                            Id = 8,
                            AssignedOrders = "[]",
                            FaultMessage = "No power",
                            IsOperational = false,
                            Location = "C1.05",
                            Name = "EQ132132",
                            Operator = "",
                            OverallEquipmentEffectiveness = 41.200000000000003,
                            State = "RED"
                        },
                        new
                        {
                            Id = 9,
                            AssignedOrders = "[]",
                            FaultMessage = "",
                            IsOperational = true,
                            Location = "D1.09",
                            Name = "EQ456484",
                            Operator = "",
                            OverallEquipmentEffectiveness = 86.900000000000006,
                            State = "YELLOW"
                        },
                        new
                        {
                            Id = 10,
                            AssignedOrders = "[3333]",
                            CurrentOrder = 3333,
                            FaultMessage = "",
                            IsOperational = true,
                            Location = "D1.05",
                            Name = "EQ741874",
                            Operator = "EMP365 - FirstName7 LastName7 ",
                            OverallEquipmentEffectiveness = 81.400000000000006,
                            State = "GREEN"
                        },
                        new
                        {
                            Id = 11,
                            AssignedOrders = "[]",
                            FaultMessage = "",
                            IsOperational = true,
                            Location = "D1.03",
                            Name = "EQ896214",
                            Operator = "EMP547 - FirstName8 LastName8 ",
                            OverallEquipmentEffectiveness = 86.200000000000003,
                            State = "RED"
                        },
                        new
                        {
                            Id = 12,
                            AssignedOrders = "[]",
                            FaultMessage = "",
                            IsOperational = true,
                            Location = "E2.01",
                            Name = "EQ745635",
                            Operator = "EMP874 - - FirstName9 LastName9 ",
                            OverallEquipmentEffectiveness = 77.0,
                            State = "YELLOW"
                        },
                        new
                        {
                            Id = 13,
                            AssignedOrders = "[4444]",
                            CurrentOrder = 4444,
                            FaultMessage = "",
                            IsOperational = true,
                            Location = "E2.02",
                            Name = "EQ555555",
                            Operator = "EMP852 - FirstName10 LastName10 ",
                            OverallEquipmentEffectiveness = 79.400000000000006,
                            State = "GREEN"
                        },
                        new
                        {
                            Id = 14,
                            AssignedOrders = "[]",
                            FaultMessage = "A very long error message about the equipment fault",
                            IsOperational = false,
                            Location = "E2.03",
                            Name = "EQ785412",
                            Operator = "EMP854 - FirstName11 LastName11  ",
                            OverallEquipmentEffectiveness = 6.4000000000000004,
                            State = "RED"
                        },
                        new
                        {
                            Id = 15,
                            AssignedOrders = "[]",
                            FaultMessage = "",
                            IsOperational = true,
                            Location = "F6.11",
                            Name = "EQ951375",
                            Operator = "EMP965 - FirstName12 LastName12 ",
                            OverallEquipmentEffectiveness = 66.700000000000003,
                            State = "YELLOW"
                        },
                        new
                        {
                            Id = 16,
                            AssignedOrders = "[5555]",
                            CurrentOrder = 5555,
                            FaultMessage = "",
                            IsOperational = true,
                            Location = "F7.17",
                            Name = "EQ749625",
                            Operator = "EMP148 - FirstName13 LastName13 ",
                            OverallEquipmentEffectiveness = 83.599999999999994,
                            State = "GREEN"
                        });
                });

            modelBuilder.Entity("EquipmentManagementPlatform.Repository.Entity.EquipmentHistoricStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeOfChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EquipmentHistoricState");
                });

            modelBuilder.Entity("EquipmentEntityEquipmentHistoricStateEntity", b =>
                {
                    b.HasOne("EquipmentManagementPlatform.Repository.Entity.EquipmentEntity", null)
                        .WithMany()
                        .HasForeignKey("EquipmentEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquipmentManagementPlatform.Repository.Entity.EquipmentHistoricStateEntity", null)
                        .WithMany()
                        .HasForeignKey("HistoricStatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
